name: Conservación de Islas
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/descarga_datos .
    - name: Ejecuta objetivo principal del Makefile
      run: docker run islasgeci/descarga_datos make
    - name: Verifica formato
      run: docker run islasgeci/descarga_datos make format
